### ISSUE TITLE
Duplicate items

### ISSUE THREAD

**Issue by sebet** [rjaviervega/tree-view-git-modified#1]
Not sure why but sometimes the modified list displays duplicate items (see `utils.php`):

![captura de ecra 2015-07-6 as 15 22 47](https://cloud.githubusercontent.com/assets/1154179/8524515/a882bc88-23f3-11e5-9e3f-0dc83a2a04d8.png)

Note: There's only one file named `utils.php` in the project.

Congrats on the idea.

**Comment by rjaviervega** [comment]
Thanks for pointing this out. I will review it and fix it ASAP. Cheers
