### ISSUE TITLE
Modified file list showing items from .gitignore

### ISSUE THREAD

**Issue by MattFlower** [rjaviervega/tree-view-git-modified#11]
I've noticed that this plugin generally processes .gitignore correctly.  However, it seems to be showing ignored files in a project with a .gitignore containing:

    */node_modules/*

It seems to work correctly with "node_modules" or "node_modules/*", but not with "*/node_modules" or "*/node_modules/*".  Unfortunately, the hundreds of files in nodemodules makes atom run incredibly slowly when I'm working on that particular code base.

**Comment by rjaviervega** [comment]
Hi @MattFlower this plugin uses components from Atom core to fetch repositories data and find out modified files. This looks more like a bug on Atom core libraries than this plugin alone. I will if I can pass the issue down to the Atom developers.
