### ISSUE TITLE
Suggestion: Option to display below the tree view?

### ISSUE THREAD

**Issue by Gruntfuggly** [rjaviervega/tree-view-git-modified#12]
I find that often I have modified a file so that when I next double click in the tree view, the file gets autosaved, and then tree-view-git-modified adds the file to it's list, and therefore moves all the files in the tree view down a line - resulting in opening the file above the one I was hoping to open.

Is it possible there could be an option to display the list below the tree view so that the above doesn't happen?

**Comment by rjaviervega** [comment]
Sure, that sounds like a good idea. I will look into implementing it shortly. Thx!

**Comment by rjaviervega** [comment]
This was done by someone else contribution.
