### ISSUE TITLE
Modified files are not found anymore

### ISSUE THREAD

**Issue by shoesel** [rjaviervega/tree-view-git-modified#13]
In Atom 1.8.0 (and I think in the previous 1.7.3 as well) the tree view panel has no content anymore.
I have attached a screenshot and I hope it's not related to other packages I use.

Would be great to get it fixed, I really like this package!

![atom-gitmodified-bug](https://cloud.githubusercontent.com/assets/2435094/15888874/fde16268-2d68-11e6-9d41-0e41831c208b.png)

**Comment by rjaviervega** [comment]
Thank you for reporting this, I will updated it when I have some time. Cheers.

**Comment by shoesel** [comment]
Seems to be ok again with version 0.6.3 on atom 1.8.0. Thanks

**Comment by shoesel** [comment]
It's just not picking up workspace changes :(

**Comment by rjaviervega** [comment]
Ok I updated the package and it should all be working fine on 0.6.4. Try it out! Cheers
