### ISSUE TITLE
File list failing to display after Atom 1.17 update.

### ISSUE THREAD

**Issue by nihiven** [rjaviervega/tree-view-git-modified#22]
I just updated to Atom 1.17.0 x64 and now git tree view is failing to open. 

**Error**
tree-view-git-modified-view.coffee:63 
Uncaught (in promise) TypeError: Cannot read property 'style' of null
at .atom/packages/tree-view-git-modified/lib/tree-view-git-modified-view.coffee:63:64

**Here is the code**
![image](https://cloud.githubusercontent.com/assets/800509/26156927/d2d713d4-3ae5-11e7-9b6d-99a0d862cacb.png)

**Atom Packages**
atom-solarized-dark-ui@0.28.0
atom-terminal@0.8.0
busy-signal@1.4.1
es6-javascript@1.0.0
intentions@1.1.2
linter@2.1.4
linter-eslint@8.1.7
linter-ui-default@1.5.0
meteor-api@2.20.0
minimap@4.28.2
minimap-find-and-replace@4.5.2
minimap-git-diff@4.3.1
platformio-ide-terminal@2.5.0
solarized-dark-ui@0.3.2
solarized-one-dark-syntax@1.1.0
sync-settings@0.8.1
todo-show@1.11.0
tree-view-git-modified@0.7.2

Maybe this has something to do with Docks?

**Comment by amdluigi** [comment]
patched

**Comment by nihiven** [comment]
Excellent. I've updated and everything is working with Atom 1.19-beta2

**Comment by amdluigi** [comment]
happy for it
;-)
