### ISSUE TITLE
Increased length of tree-view not taken into account for scrolling

### ISSUE THREAD

**Issue by michaelaye** [rjaviervega/tree-view-git-modified#3]
When the Git Modified section is large enough to push the end of the tree-view out of sight, tree-view does **not** trigger the scrolling interface and stays static even so files are out of view. Should this plugin maybe communicate the length of file list somehow to the tree-view plugin?

I attach some screenshots, even so I'm not sure they help as they don't prove that scrolling does not work, but one can see how the last files of the standard tree-view are now out of sight:

![screenshot 2015-07-27 12 19 12](https://cloud.githubusercontent.com/assets/69774/8914014/e27905e8-3459-11e5-80c5-0b71bcbb03ea.png)
![screenshot 2015-07-27 12 19 18](https://cloud.githubusercontent.com/assets/69774/8914018/e895da82-3459-11e5-8ee6-58779491ebea.png)

**Comment by rjaviervega** [comment]
Thank you for finding this bug. I will fix it shortly.
